Story_8/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story9/', include('story9.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path('', index),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginUser, name='loginUser'),
    path('loginFinish/', views.loginFinish , name ='loginFinish'),
    path('logout/', views.logout_user, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

class Data(models.Model):
    title = models.CharField(max_length = 100)
    author = models.CharField(max_length = 100)
    likes = models.IntegerField()

    class Meta:
        ordering = ['-likes']
        
    def __str__(self):
        return self.title

story9/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .models import Data
from django.core import serializers
from django.http import JsonResponse

# Create your views here.
@csrf_exempt
def index(request):

    top5 = {'context' : Data.objects.all()[:5]}
    if request.method == 'POST':
        title = request.POST["title"]
        author = request.POST["author[]"]
    else:
        Data.objects.all().delete()

    return render(request, 'main/index.html', top5)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect

# Create your views here.

def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'home.html')
    else:
        form = UserCreationForm()

    form = UserCreationForm()

    return render(request, 'signup.html', { 'form':form })

def loginUser(request):
    response = {}
    if request.method == "POST":
        user_id = request.POST['user_id']
        password = request.POST['password']
        user = authenticate(request, username=user_id, password=password)
        if user:
            login(request, user)
            return redirect('story9:loginFinish')
        else:
            response["user_not_found"]= "User doesn't exist"
            return render(request, 'login.html', response) 
    else:         
        return render(request,'login.html',response)

def loginFinish(request):
    response = {}
    response['user'] = request.user
    return render(request, 'logout.html', response)

def logout_user(request):
    if request.method == "POST":
        logout(request)
    return redirect('story9:loginUser')

main/templates/main/index.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>Story 8 Rizma</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
	<div class="container">
	<h1>Find Books Here</h1>

	<!-- <div class="col-md-6 col-md-offset-3">
		<div class="row">
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
				Top 5 Books
			</button>
		</div>
	</div>
	<br>
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
			<h5 class="modal-title" id="exampleModalLabel">Top 5 Liked Books</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			</div>
			<div class="modal-body">
			
			</div>
			<div class="modal-footer">
			<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
		</div>
	</div> -->

	<input id="search">
	<button id="searchbutton" type="button">Search</button>
	
	<table class="table table-bordered" id="demo">
	</table>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
			var putResult
            var bookData
            var btn
            
            window.onload = function() {
                btn = document.getElementById("searchbutton")
                putResult = document.getElementById("demo");
            
                btn.addEventListener("click", function(){
                    var ourRequest = new XMLHttpRequest();
                    var userKeyword= document.getElementById("search").value;
                    ourRequest.open('GET', 'https://www.googleapis.com/books/v1/volumes?q='+userKeyword)
                    
                    ourRequest.onload= function () {
                        bookData = JSON.parse(ourRequest.responseText)
                        try{
                            renderHTML(bookData)
                        }
                        catch (err){
                            
                        }
                    };
                    ourRequest.send()
            
                })
            }   
            
                function NoAuthor(author) {
                    if (author == undefined){
                        return "Author Not Found"
                    }
                    else
                        return author
                }
                
                function renderHTML(data) {
                    var table="<thead><tr><th>Cover</th><th>Description</th></tr></thead><tbody>";

                    for (i = 0; i < data.items.length; i++) {

                        table += "<tr><td>" + 
                        "<img src='"+ data.items[i].volumeInfo.imageLinks.smallThumbnail +"'>"+ "</td><td>" +
                        "<b>Title:</b> " + data.items[i].volumeInfo.title + "<br>" +
                        "<b>Author:</b> " + NoAuthor(data.items[i].volumeInfo.authors) + "<br>" +
                        "<b>Publisher:</b> " + data.items[i].volumeInfo.publisher + "<br>" +
                        "<b>Published Date:</b> " + data.items[i].volumeInfo.publishedDate + "<br>" +
                        "<b>Description:</b> " + data.items[i].volumeInfo.description + "<br>" +
                        "<b>Preview Link:</b> " + data.items[i].volumeInfo.previewLink + "<br>" +
                        "<b>Info Link:</b> " + data.items[i].volumeInfo.infoLink
                        + "</td>";
                        
                      
                    }
                    table += "</tbody>" 
                    putResult.innerHTML = table;                   

                }

                function AuthorHandling(author) {
                    if (author == undefined){
                        var AuthorArray = ["Author Not Found"]
                        return AuthorArray
                    }
                    else
                        return author
                }
            

                
</script>


</body>
</html>

story9/templates/home.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Story9</title>

</head>

<body>
    <h1>Hello there!</h1>
    <p><a href="{%url 'story9:signup'%}">Sign Up</a> / <a href="{%url 'story9:loginUser'%}">Login</a></p>
</body>


</html>

story9/templates/login.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Story9</title>

</head>

<div style="text-align: center;" class="status">
  <p class="h1" style="text-align: center;">Login</p>

  <form action="" method="POST">
      {% csrf_token %}
      <div class="mb-2">
          <input type="user_id" name="user_id" id="user_id" placeholder="Username" required>
      </div>
      <div>
          <input type="password" name="password" id="password" placeholder="Password" required>
      </div>
          <p>
              {{user_not_found}}
          </p>
      <button class="btn-secondary" id="login_button">Sign in</button>
      
  </form>
</div>



</html>

story9/templates/logout.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Story9</title>

</head>

<body>
    <div style="text-align: center;">
        <p class="h1 mt-5 mb-3">Hi {{user.username}} Selamat Datang di Website ini</p> 
    </div>

    <div class="status" style="text-align: center;">
        <form action='/story9/logout/' method="POST">
            {%csrf_token%}
            <button class="btn-secondary" type="submit">Logout</button>
        </form>
    </div>

</body>



</html>

story9/templates/signup.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Story 10 Adham Miftah</title>

</head>

<body>
    <h1>Sign Up</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Sign Up</button>
    </form>
</body>


</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- My Font -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <title>Rizma C</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-custom navbar-fixed-top">
      <div class="container">
          <h3 class="logo">RIZMA C</h3>
          <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home' %}">HOME <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home'%}#section2">ABOUT ME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:contact'%}">CONTACT</a>
              </li>
            </ul>
          </div>
      </div>
    </nav>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
  {% block content %}
  {% endblock content %}
</html>